version: 2
jobs:
    tag_job:
        # This is a directory where all your repo content will be placed.
        # Name is not that important at this case.
        working_directory: ~/build

        # Docker environment where we gonna run our build deployment scripts
        docker:
            - image: circleci/node:10-jessie

        steps:
            - checkout # checkout repo contents
            - run:
                  name: Installing NPM dependencies
                  working_directory: ~/build
                  command: |
                      cd ~/build/run-stats && yarn install --production
            - run:
                  name: Run stats
                  command: |
                      set -eu # stop on error
                      node ~/build/get-stats/
workflows:
    version: 2
    build_tag:
        jobs:
            - tag_job:
                  filters:
                      tags:
                          only: /^v.*/
