version: 2
jobs:
    tag_job:
        # This is a directory where all your repo content will be placed.
        # Name is not that important at this case.
        working_directory: ~/build

        # Docker environment where we gonna run our build deployment scripts
        docker:
            - image: circleci/node:10-jessie

        steps:
            - checkout # checkout repo contents
            - run:
                  name: Installing NPM dependencies
                  working_directory: ~/build
                  command: |
                      cd ~/build/run-stats && yarn install --production
            - run:
                  name: Run stats
                  command: |
                      set -eu # stop on error
                      GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN} node ~/build/run-stats/
workflows:
    version: 2
    build_tag:
        jobs:
            - tag_job:
                  filters:
                      # ignore any commit on any branch by default
                      branches:
                          ignore: /.*/
                      # only act on version tags
                      tags:
                          only: /^v.*$/
